### ISSUE TITLE
call to undeclared function '__assert_rtn'

### ISSUE THREAD

**Issue by basmagamil** [trustdecision/trustdevice-ios#14]
I get this issue while trying to build my app in release mode after integrating this library (it successfully builds in debug)
I'm using this in an ios native module used in a react native app via a bridge

```
❌ /Users/vagrant/git/ios/Pods/TrustDecision/TrustDecision/Classes/TDMobRiskManager.m:99:9: call to undeclared function '__assert_rtn'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        __assert_rtn(__func__, ("unknown"), 0, assertDescription);
```

It's running on `xcode 15.2`

**Comment by zeinber** [comment]
Hey guy, looking at the error message, the header file related to __assert_rtn is missing. 
You can try adding # import<assert. h> to the header of the reference code.

**Comment by basmagamil** [comment]
@zeinber Hey, thanks for replying! 
adding `# import <assert.h>` didn't solve it, but redefining the header for `__assert_rtn` in `TDMobRiskManager.m` solved it, like so
`extern void __assert_rtn(const char *, const char *, int, const char *);`
I did a patch for the library to pass the build error but can you add the fix to the library as to avoid the patch?

**Comment by zeinber** [comment]
Okay, it seems that the react-native compilation environment does not explicitly declare this symbol by default. In the native compilation environment, it works.
I will merge this change, thank you for your feedback！！
